# Docker
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure for Students(eae96d2d-5742-4098-88df-1e1919e65606)'
    appType: 'webAppLinux'
    appName: 'practicalab11'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
